### ISSUE TITLE
Clearup the author

### ISSUE THREAD

**Issue by l-2-j** [EIA485/NeosPrivacyShield#1]
I've got no issues with forks of my projects (to clarify, when they follow the license like yours 😄), but I'd appreciate if they didn't look like they're from me. I'd ask that you remove/change my name from [AssemblyCompany](https://github.com/EIA485/NeosPrivacyShield/blob/fcd0eb803271e34f1ef048c467e492a5af61ace3/PrivacyShield/Properties/AssemblyInfo.cs#L10) and [`xyz.ljoonal.neos.privacyshield` from the harmony instance](https://github.com/EIA485/NeosPrivacyShield/blob/fcd0eb803271e34f1ef048c467e492a5af61ace3/PrivacyShield/PrivacyShield.cs#L18) ([afaik unpatching becomes a major problem for example too with duplicate identifiers](https://harmony.pardeike.net/articles/basics.html#unpatching)).

An additional note that I won't ask, but want to add if any people are reading this and thinking about forking one of my projects: It'd be nice for the name to indicate that it's a fork so I can quickly reject issues from my issue tracker when they're for/from forks.

**Comment by EIA485** [comment]
oop, sorry about that. oversight on my end. fixed in commit [6c76591](https://github.com/EIA485/NeosPrivacyShield/commit/6c76591ac5ede845a8c61dbaa334a396ffdf061a)
